services:
  postgres:
    image: library/postgres:18-alpine
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes
      POSTGRES_DB: hermes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hermes -d hermes"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: library/redis:8-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    profiles:
      - rabbitmq
    image: library/rabbitmq:4.3-management
    container_name: hermes-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: hermes
      RABBITMQ_DEFAULT_PASS: hermes
      RABBITMQ_DEFAULT_VHOST: /
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  pgdata: